package com.github.forax.allocagent.agent;

import java.io.BufferedWriter;
import java.io.IOException;
import java.lang.instrument.Instrumentation;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;

import static java.nio.file.StandardOpenOption.CREATE;
import static java.nio.file.StandardOpenOption.TRUNCATE_EXISTING;
import static java.nio.file.StandardOpenOption.WRITE;

/**
 * Loaded by the BOOTSTRAP class loader (see Agent.premain, which appends a
 * jar containing only this class via
 * Instrumentation.appendToBootstrapClassLoaderSearch). This is what lets
 * instrumented JDK classes -- which are themselves bootstrap-loaded and
 * can't see application/agent classloaders -- resolve and call this class.
 * <p>
 * CONSEQUENCES OF THIS:
 * - Only ever reference java.* / core JDK classes here. Any dependency on
 *   ASM or on other agent classes will blow up with NoClassDefFoundError,
 *   because the bootstrap loader can't see the system classloader's classes.
 * - All members called from generated bytecode must be `public`. Java
 *   access control for package-private members is scoped to
 *   (package name + defining classloader); Agent and Probe share a package
 *   name but NOT a defining loader, so package-private access would throw
 *   IllegalAccessError at runtime.
 */
public final class Probe {

  private static final Object LOCK = new Object();
  private static int COUNTER;

  private Probe() {}

  private static final class Injection {
    final BufferedWriter writer;
    final Instrumentation instrumentation;

    Injection(BufferedWriter writer, Instrumentation instrumentation) {
      this.writer = writer;
      this.instrumentation = instrumentation;
    }
  }

  private static final ThreadLocal<Injection> INJECTION = new ThreadLocal<>();

  private static final class Constants {
    static final BufferedWriter WRITER;
    static final Instrumentation INSTRUMENTATION;

    static {
      var injection = INJECTION.get();
      WRITER = injection.writer;
      INSTRUMENTATION = injection.instrumentation;
    }
  }

  public static void init(String agentArgs, Instrumentation inst) {
    Objects.requireNonNull(inst);

    var path = (agentArgs == null || agentArgs.isBlank()) ? "allocations.log" : agentArgs;
    BufferedWriter writer;
    try {
      var file = Path.of(path);
      writer = Files.newBufferedWriter(file, StandardCharsets.UTF_8,
          CREATE, TRUNCATE_EXISTING, WRITE);
    } catch (IOException e) {
      System.err.println("[allocation-agent] could not open log file '" + path + "': " + e);
      return;
    }
    INJECTION.set(new Injection(writer, inst));
    Runtime.getRuntime().addShutdownHook(new Thread(Probe::close));
  }

  /**
   * @param object           the allocated object
   * @param className        class containing the allocation site (dot form)
   * @param methodName       method containing the allocation site
   * @param methodDescriptor JVM descriptor of that method, e.g. "(I)Ljava/lang/String;"
   */
  public static void arrayAllocation(Object object, String className, String methodName, String methodDescriptor) {
    var writer = Constants.WRITER;

    synchronized (LOCK) {
      var counter = COUNTER++;
      var size = Constants.INSTRUMENTATION.getObjectSize(object);
      var line = counter + ":" + Thread.currentThread().getName() + ":"
          + className + ":" + methodName + methodDescriptor + ":" + size;
      try {
        writer.write(line);
        writer.newLine();
      } catch (IOException ignored) {
      }
    }
  }

  /**
   * @param type             the allocated object type
   * @param className        class containing the allocation site (dot form)
   * @param methodName       method containing the allocation site
   * @param methodDescriptor JVM descriptor of that method, e.g. "(I)Ljava/lang/String;"
   */
  public static void objectAllocation(String type, String className, String methodName, String methodDescriptor) {
    var writer = Constants.WRITER;

    synchronized (LOCK) {
      var counter = COUNTER++;
      var line = counter + ":" + Thread.currentThread().getName() + ":"
          + className + ":" + methodName + methodDescriptor + ":" + type;
      try {
        writer.write(line);
        writer.newLine();
      } catch (IOException ignored) {
      }
    }
  }

  private static void close() {
    var writer = Constants.WRITER;
    if (writer != null) {
      try {
        writer.flush();
        writer.close();
      } catch (IOException ignored) {
      }
    }
  }
}